---
- name: Update apt packages
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - docker.io
      - docker-compose
      - git
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Create swap file
  command: fallocate -l 2G /swapfile
  args:
    creates: /swapfile

- name: Set swap permissions
  file:
    path: /swapfile
    mode: '0600'

- name: Make swap
  command: mkswap /swapfile
  args:
    creates: /swapfile

- name: Enable swap
  command: swapon /swapfile
  ignore_errors: yes

- name: Expand root partition
  command: growpart /dev/nvme0n1 1
  ignore_errors: yes

- name: Resize filesystem
  command: resize2fs /dev/nvme0n1p1
  ignore_errors: yes
