apiVersion: v1
kind: Secret
metadata:
  name: tradestack-secrets
type: Opaque
stringData:
  DB_HOST: postgres
  DB_NAME: tradestack
  DB_USER: tradestack
  DB_PASSWORD: tradestack123
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  GRAFANA_PASSWORD: tradestack123
