apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: tradestack
    user: tradestack
    secureJsonData:
      password: tradestack123
    jsonData:
      sslmode: disable
    isDefault: true
